Make psalm happy by casting to string
This is always a string, but because the parent class says it's
`null|string`, we cannot just override the type here (this gives another
error: NonInvariantDocblockPropertyType).

Casting to a string is safe though since we know it's always a string
anyway.